-- models/dim_state.sql
with
    state_data as (
        select distinct state as state_code from {{ source("STAGED", "STA_INDIV") }} where state is not null
    )

select
    row_number() over (order by state_code) as state_key,
    state_code,
    case
        state_code
        when 'AL'
        then 'Alabama'
        when 'AK'
        then 'Alaska'
        when 'AZ'
        then 'Arizona'
        when 'AR'
        then 'Arkansas'
        when 'CA'
        then 'California'
        when 'CO'
        then 'Colorado'
        when 'CT'
        then 'Connecticut'
        when 'DE'
        then 'Delaware'
        when 'FL'
        then 'Florida'
        when 'GA'
        then 'Georgia'
        when 'HI'
        then 'Hawaii'
        when 'ID'
        then 'Idaho'
        when 'IL'
        then 'Illinois'
        when 'IN'
        then 'Indiana'
        when 'IA'
        then 'Iowa'
        when 'KS'
        then 'Kansas'
        when 'KY'
        then 'Kentucky'
        when 'LA'
        then 'Louisiana'
        when 'ME'
        then 'Maine'
        when 'MD'
        then 'Maryland'
        when 'MA'
        then 'Massachusetts'
        when 'MI'
        then 'Michigan'
        when 'MN'
        then 'Minnesota'
        when 'MS'
        then 'Mississippi'
        when 'MO'
        then 'Missouri'
        when 'MT'
        then 'Montana'
        when 'NE'
        then 'Nebraska'
        when 'NV'
        then 'Nevada'
        when 'NH'
        then 'New Hampshire'
        when 'NJ'
        then 'New Jersey'
        when 'NM'
        then 'New Mexico'
        when 'NY'
        then 'New York'
        when 'NC'
        then 'North Carolina'
        when 'ND'
        then 'North Dakota'
        when 'OH'
        then 'Ohio'
        when 'OK'
        then 'Oklahoma'
        when 'OR'
        then 'Oregon'
        when 'PA'
        then 'Pennsylvania'
        when 'RI'
        then 'Rhode Island'
        when 'SC'
        then 'South Carolina'
        when 'SD'
        then 'South Dakota'
        when 'TN'
        then 'Tennessee'
        when 'TX'
        then 'Texas'
        when 'UT'
        then 'Utah'
        when 'VT'
        then 'Vermont'
        when 'VA'
        then 'Virginia'
        when 'WA'
        then 'Washington'
        when 'WV'
        then 'West Virginia'
        when 'WI'
        then 'Wisconsin'
        when 'WY'
        then 'Wyoming'
        -- Include additional cases for other territories or commonwealths if needed
        else 'Unknown'
    end as state_name
from state_data
